# Generated by Django 4.0.2 on 2022-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220215_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
